# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d29f391c9ef4de0fb580f02d0cbaa03594aa7aec389c61eb8b34b7fac9912917ffed82485873fc46d444eef8e337e778d4b47cb31f62a59b84bc77e9f648013

test:
  secret_key_base: 45965e73d35d3433274aadc519c00f32848e7d73fa21b12e2370698e4eb3764d7aab0b00bcad8a458fb1c2b7a3d0e01aa039b44ad509e1f3b3df82e81fa1543c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
